export const APP_NAME = "EventPro";
export const APP_VERSION = "1.0.0";
export const MODULE_CODE = "B9IS130";

export const CATEGORIES = [
    { value: "all", label: "All Events", emoji: "🎪" },
    { value: "music", label: "Music", emoji: "🎵" },
    { value: "technology", label: "Technology", emoji: "💻" },
    { value: "sports", label: "Sports", emoji: "⚽" },
    { value: "art", label: "Art & Culture", emoji: "🎨" },
    { value: "food", label: "Food & Drink", emoji: "🍕" },
    { value: "business", label: "Business", emoji: "💼" },
    { value: "health", label: "Health & Wellness", emoji: "🧘" },
    { value: "education", label: "Education", emoji: "📚" },
    { value: "networking", label: "Networking", emoji: "🤝" },
];
export const SEED_EVENTS = [
                    {
        id: "evt-001",
        title: "Dublin Tech Summit 2026",
        description:
            "Ireland's premier technology conference bringing together innovators, developers, and entrepreneurs. Featuring keynotes from leading tech companies, workshops on AI/ML, cloud computing, and hands-on coding sessions. A must-attend for anyone in the tech industry.",
        category: "technology",
        date: "2026-04-15",
        time: "09:00",
        location: "Convention Centre Dublin",
        city: "Dublin",
        country: "Ireland",
        lat: 53.3498,
        lng: -6.2603,
        price: 149,
        capacity: 800,
        attendees: 523,
        image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
        organizer: "TechIreland",
        organizerId: "user-admin",
        tags: ["AI", "Cloud", "Networking", "React"],
        isFeatured: true,
        createdAt: "2026-01-10T10:00:00Z",
    },
    {
        id: "evt-002",
        title: "The Midnight Orchestra",
        description:
            "An evening of classical and contemporary music performed by the National Symphony Orchestra of Ireland. Featuring works by Beethoven, Debussy, and world premieres by Irish composers. Dress code: Smart Casual.",
        category: "music",
        date: "2026-04-22",
        time: "19:30",
        location: "National Concert Hall",
        city: "Dublin",
        country: "Ireland",
        lat: 53.3358,
        lng: -6.2603,
        price: 45,
        capacity: 1200,
        attendees: 980,
        image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
        organizer: "NSO Ireland",
        organizerId: "user-admin",
        tags: ["Classical", "Orchestra", "Live Music"],
        isFeatured: true,
        createdAt: "2026-01-15T10:00:00Z",
    },
     {
        id: "evt-003",
        title: "Web Dev Bootcamp – React & Node",
        description:
            "A 2-day intensive workshop covering modern full-stack development with React 19, Node.js, Express, and MongoDB. Perfect for students and junior developers looking to level up their skills.",
        category: "education",
        date: "2026-05-03",
        time: "10:00",
        location: "DCU Alpha, Glasnevin",
        city: "Dublin",
        country: "Ireland",
        lat: 53.3872,
        lng: -6.2579,
        price: 0,
        capacity: 60,
        attendees: 47,
        image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80",
        organizer: "DCU CodeClub",
        organizerId: "user-admin",
        tags: ["React", "Node.js", "Free", "Workshop"],
        isFeatured: true,
        createdAt: "2026-02-01T10:00:00Z",
    },

];

export const STORAGE_KEYS = {
    USER: "ep_user",
    TOKEN: "ep_token",
    EVENTS: "ep_events",
    BOOKINGS: "ep_bookings",
};
